services:
  gnu-mpich:
    image: testsuite/gnu-mpich
    # env_file:
    #   - ./gnu-mpich/.env.gnu-mpich
    build:
      dockerfile: gnu-mpich/Dockerfile
      args:
        MPICH: 4.1.2
        HDF5: 1.12.0
        PNETCDF: 1.12.3
        HYPRE: 2.24.0
        # I would prefer to do this so I can parse the env files
        # to generate float text in the flashTest-view but podman isn't happy
        # with specifying an env_file that isn't .env, which seems to get loaded no matter what...
        # MPICH: ${MPICH}
        # HDF5: ${HDF5}
        # PNETCDF: ${PNETCDF}
        # HYPRE: ${HYPRE}
    hostname: gnu-mpich

  gnu-mpich-tester:
    stdin_open: true
    tty: true
    cpu_count: 4
    image: testsuite/gnu-mpich/tester
    env_file: .env
    depends_on: gnu-mpich
    build:
      dockerfile: gnu-mpich/Dockerfile.tester
      args:
        MYUSER: ${MYUSER}
    hostname: gnu-mpich
    environment:
      - LOGNAME=gnu-mpich
    volumes:
      - ${SSH_DIR}:/mnt/ssh:Z
      - ${FLASHDEPS_DIR}:/local:z
      - ${OUTPUT_DIR}:/outputdir:z
      - ${MAINARCHIVE_DIR}:/mainArchive:z
    command: "/local/runTest.sh ${MYUSER} ${VM} ${TESTFILE} ${BRANCH} ${VIEWARCH}"

  gnu-mpich-docs:
    image: testsuite/gnu-mpich/docs
    env_file: .env
    depends_on: gnu-mpich
    build:
      dockerfile: gnu-mpich/Dockerfile.docs
      args:
        MYUSER: ${MYUSER}
    hostname: gnu-mpich
    volumes:
      - ${SSH_DIR}:/mnt/ssh:Z
      - ${FLASHDEPS_DIR}:/local:z
    command: "/local/autoDocs.sh ${MYUSER}"

  intel:
    image: testsuite/intel
    # env_file:
    #   - ./intel/.env.intel
    build:
      dockerfile: intel/Dockerfile
      args:
        HDF5: 1.12.0
        PNETCDF: 1.12.3
        HYPRE: 2.30.0
    hostname: intel

  intel-tester:
    cpu_count: 4
    image: testsuite/intel/tester
    env_file: .env
    depends_on: intel
    build:
      dockerfile: intel/Dockerfile.tester
      args:
        MYUSER: ${MYUSER}
    hostname: intel
    environment:
      - LOGNAME=intel
    volumes:
      - ${SSH_DIR}:/mnt/ssh:Z
      - ${FLASHDEPS_DIR}:/local:z
      - ${OUTPUT_DIR}:/outputdir:z
      - ${MAINARCHIVE_DIR}:/mainArchive:z
    command: "/local/intel/entrypoint.sh ${MYUSER} intel ${TESTFILE} ${BRANCH} ${VIEWARCH}"

