FROM testsuite/gnu-mpich

ARG MYUSER

RUN apt-get update && apt-get -y install \
    rsync

# volume /my/host/dir:/mnt:Z only like when we're root for w/e reason
WORKDIR /home/${MYUSER}
ENTRYPOINT ["/bin/bash"]
